language: csharp
mono: 5.2.0
dotnet: 3.0.100-preview4-011223
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - libunwind8-dev

before_install:
  - nvm install 10.12.0
  - nvm use 10.12.0
  # Yarn
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn
  
script:
 - echo "Running tests"
 - travis_wait dotnet run -p Fable.Remoting.Json.Tests/Fable.Remoting.Json.Tests.fsproj
 - travis_wait dotnet run -p Fable.Remoting.Server.Tests/Fable.Remoting.Server.Tests.fsproj
 - travis_wait dotnet run -p Fable.Remoting.Suave.Tests/Fable.Remoting.Suave.Tests.fsproj
 - travis_wait dotnet run -p Fable.Remoting.Giraffe.Tests/Fable.Remoting.Giraffe.Tests.fsproj
 - travis_wait ./build.sh IntegrationTests
 - travis_wait ./build.sh IntegrationTestsV2
 - travis_wait ./build.sh RunDotnetClientTests
