init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

environment:
  nodejs_version: "12.16.1"

cache:
  - "%LOCALAPPDATA%\\Yarn"

os: Visual Studio 2019 Preview

# Install scripts. (runs after repo cloning)
install:
  # install latest dotnet 6 sdk
  - cmd: choco install dotnet-sdk --pre --version 6.0.100-rc12145832
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version

  # # Update npm
  # # There seems to be issues with npm 5.4 in Windows
  # # See https://github.com/npm/npm/issues/18380
  # - npm install -g npm@6.1.0

build_script:
  - cmd: dotnet tool restore
  - cmd: dotnet fake build -t BuildRunAllTests
  - cmd: dotnet fake build -t IntegrationTests
  - cmd: dotnet fake build -t IntegrationTestsNagareyama

test: off
